#!/bin/sh

case "$1" in
    start) 
        cd /lib/modules/6.1.44/extra/
        echo "Loading aesd char driver"
        aesdchar_load
        ;;
    stop) 
        cd /lib/modules/6.1.44/extra/
        echo "Unloading aesd char driver"
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac